### ISSUE TITLE
Any playlist functionality

### ISSUE THREAD

**Issue by wittilywish** [irbyk/Plex-Discord-Bot_V2#1]
Thanks again for the bot installation help from a few weeks ago.

I had a question on the playlist commands. I tried using them, and they do not seem to work properly. I tried typing in the name of a playlist as it appears on my plex account (e.g. "Rock"), but it does not work.

Am I using this function correctly, or is there the ability to type in the playlist name form the plex account to be played? Right now, I have to manually queue up every song I want played using the discord commands which takes a lot of time.

Thanks.

**Comment by irbyk** [comment]
You cannot use your plex playlist unfortunately. You have to make them manually for the bot. 

use `!playlist create name_of_your_playlist` without space for the name.
then use `!playlist add name_of_your_playlist name of your song` to add one song to your new playlist.
finally use `!playlist play name_of_your_playlist` to play it :).

You can use `!playlist ?` to get the command help for the playlist

Note :
`!` is the default character to call the bot, you may have changed yours in the config file
Be sure to use the last update of the bot (I put one online last day with `!youtube` command and a fix to the `create` command which was `creat` before ^^').

Edit : I close this issue, but if you have more questions, you can find me on Discord here : https://discord.gg/c39aRhB

**Comment by irbyk** [comment]
I juste write this message to informe that i'm working on plex playlist support (currently you can play them on the server but that all ^^).
