### ISSUE TITLE
Possible to play music by mood?

### ISSUE THREAD

**Issue by JoshuaMunoz** [irbyk/Plex-Discord-Bot_V2#2]
I know, this sounds really dumb and nerdy, but I'm using this for D&D ambiance/music/effects and so I have all of my tracks (individually) categorized by a mood (which Plex supports).

Is it possible to add a !mood BLAH option so it can play something from the mood list instead of it being so direct, like, file name, list of songs, etc.?

----

**Comment by irbyk** [comment]
Add it in the last update.
