### ISSUE TITLE
Playing after a queue has ended

### ISSUE THREAD

**Issue by Ahawk122** [irbyk/Plex-Discord-Bot_V2#3]
Just wanted to say love the bot. I have been looking for this exact style of plex-integration. The bot functions well up until the point where it finishes a queue. Then I can use the !play command and the bot will respond by adding to a queue but the queue never plays. The only solution I have found is to restart the whole bot each time this happens. I'm probably missing something really obvious but if I could get some help I would appreciate it.

**Comment by irbyk** [comment]
It's a random issue, or it happend every time the queue end ?

**Comment by Ahawk122** [comment]
This happens consistently each time the queue ends.

**Comment by irbyk** [comment]
ok, give me 10min to fix it (I see what happen, and i forgot to push the fix on github)

**Comment by irbyk** [comment]
It should be fine now !

**Comment by Ahawk122** [comment]
Awesome! Thanks for responding so fast! What do I need to do to update the bot?

**Comment by irbyk** [comment]
Just clone the git repository/ pull hte lastest version, keep your config file and your playlist folder if you have create some playlist and that should be good !
